import { craftingStyles } from "galadrielcss"
// Importing the CSS file generated by Galadriel.CSS
import "./page.css";

export default function Home() {
  const main = craftingStyles(() => ({
    background: 'linear-gradient(to right, #485563, #29323c)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  }))

  const container = craftingStyles(() => ({
    background: '#950505',
    boxShadow: 
      'inset -27px -27px 29px #670303, inset 27px 27px 29px #c30707',
    borderRadius: '19px',
    border: '1px outset #00000084',
    boxSizing: 'border-box',
    filter: 'drop-shadow(0 0 0.75rem #4d4d4dc0)',
    fontFamily: "'Exo 2', sans-serif",
    display: 'flex',
    gap: '30px',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '40px',
    height: 'auto',
    width: 'auto',
  }))

  const titleContainer = craftingStyles(() => ({
    background: '#e27a1c',
    boxShadow: 'inset -9px -9px 18px #b76317, inset 9px 9px 18px #ff9121',
    border: '1px outset #00000084',
    borderRadius: '19px',
    boxSizing: 'border-box',
    padding: '50px 100px',
    height: 'auto',
    width: '100%',
  }))

  const title = craftingStyles(() => ({
    fontSize: '20px',
    textAlign: 'center',
    height: '100%',
    width: '100%',
  }))

  const btnContainer = craftingStyles(() => ({
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px',
    height: 'auto',
    width: '100%',
  }))

  const button = craftingStyles(() => ({
    border: '1px outset #000000a0',
    borderRadius: '19px',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 'bold',
    padding: '20px',
    height: 'auto',
    width: '45%',
  }))

  const cancel = craftingStyles(() => ({
    background: '#f1c232',
    boxShadow: 'inset -15px -15px 30px #a68623, inset 15px 15px 30px #fffe42',
    hover: {
      background: '#c59e27',
      boxShadow: 'inset -15px -15px 30px #83691a, inset 15px 15px 30px #d1d135',
    }
  }))

  const proceed = craftingStyles(() => ({
    background: '#6ef103',
    boxShadow: 'inset -15px -15px 30px #4ca602, inset 15px 15px 30px #90ff04',
    hover: {
      background: '#5bc703',
      boxShadow: 'inset -15px -15px 30px #326e01, inset 15px 15px 30px #6ec702',
    }
  }))

  return (
    <main className={main}>
      <div className={container}>
        <div className={titleContainer}>
          <p className={title}>Are you sure you want to proceed?</p>
        </div>
        <div className={btnContainer}>
          <button className={`${button} ${cancel}`}>Cancel</button>
          <button className={`${button} ${proceed}`}>Continue</button>
        </div>
      </div>
    </main>
  )
}
